export const keywords = [
  // General fashion
  "fashion",
  "clothing",
  "apparel",
  "outfit",
  "style",
  "model",
  "runway",
  "accessory",
  "wardrobe",
  "haute couture",
  "designer",
  "streetwear",
  "trendy",
  "catwalk",
  "glamour",
  "lookbook",
  "couture",
  "textile",
  "fabric",
  "ensemble",
  "attire",
  "vestment",
  "threads",
  "tailor",
  "chic",
  "elegant",
  "vogue",
  "ready-to-wear",
  "garment",
  "pattern",
  "seam",
  "fashionista",
  "boutique",
  "accessorize",
  "wardrobing",
  "minimalist fashion",
  "sustainable fashion",
  "vintage",
  "boho",
  "fashion week",
  "silhouette",
  "outfitting",
  "fashion trend",
  "luxury fashion",
  "capsule wardrobe",
  "fashion magazine",
  "runway model",
  "statement piece",

  // Hairstyle-related
  "hairstyle",
  "haircut",
  "hairdo",
  "hair fashion",
  "hair model",
  "salon",
  "barber",
  "hair trends",
  "hair color",
  "highlights",
  "balayage",
  "ombre",
  "hair styling",
  "braids",
  "curls",
  "straight hair",
  "updo",
  "buns",
  "bangs",
  "pixie cut",
  "bob cut",
  "layered hair",
  "hairstylist",
  "hair accessories",
  "headband",
  "scrunchie",
  "clip",
  "hairpin",

  // Shoe/Footwear-related
  "shoe",
  "footwear",
  "sneakers",
  "heels",
  "boots",
  "loafers",
  "sandals",
  "flats",
  "oxfords",
  "wedges",
  "platforms",
  "mules",
  "pumps",
  "slippers",
  "brogues",
  "athletic shoes",
  "designer shoes",
  "limited edition sneakers",
  "shoe trends",
  "shoe fashion",

  // Sportswear/Activewear
  "sportswear",
  "activewear",
  "athleisure",
  "gym clothes",
  "workout gear",
  "yoga pants",
  "leggings",
  "sports bra",
  "tracksuit",
  "sweatpants",
  "compression wear",
  "running shoes",
  "tennis outfit",
  "fitness fashion",
  "performance wear",
  "training wear",
  "cycling gear",
  "base layers",
  "athletic apparel",
  "stretchwear",
];
